version: '3'
services:

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./Dockerfile
    command: java -jar -Dspring.profiles.active=prod /app/core.jar
    env_file:
      - .env
    volumes:
      - ./:/app/
    expose:
      - 8080

  nginx:
    container_name: nginx
    build: ./config/nginx
    ports:
      - "80:80"
    depends_on:
      - web
