spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB}?serverTimezone=Asia/Seoul
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

  jwt:
    secret-key: ${SECRET-KEY}
    blacklist:
      access-token: BlackList_AccessToken_

  redis:
    host: ${HOST}
    port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply.lakkulakku@gmail.com
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId:
            clientSecret:
            scope:
              - email
              - profile
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: lakku-lakku.com
    region:
      static: ap-northeast-2
    stack:
      auto: false
