spring:
  datasource:
    config:
      use-legacy-processing: true
      profiles: local
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 
    username: root
    password: 

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
